/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Chrisdaniar
 */
public class framearrray extends javax.swing.JFrame {

    /**
     * Creates new form framearrray
     */
    public framearrray() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jtxtnama = new javax.swing.JTextField();
        jtxtalamat = new javax.swing.JTextField();
        jtxtusia = new javax.swing.JTextField();
        jtxtjenis = new javax.swing.JTextField();
        jtxtgol = new javax.swing.JTextField();
        jtxtstatus = new javax.swing.JTextField();
        jtxtkewar = new javax.swing.JTextField();
        jtxtspesial = new javax.swing.JTextField();
        jtxtwaktu = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 153));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Pemilihan Dokter");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(160, 10, 180, 22);

        jLabel2.setText("Dokter Spesialis");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(40, 370, 100, 20);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Piliih Salah Satu--", "DR. Farras Yassar", "DR. Anisa Putri", "DR. Harun Fajar" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox1);
        jComboBox1.setBounds(160, 60, 170, 20);

        jLabel3.setText("Pilih Dokter");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(40, 60, 100, 20);

        jLabel4.setText("Nama");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(40, 130, 100, 20);

        jLabel5.setText("Alamat");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(40, 160, 100, 20);

        jLabel6.setText("Usia");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(40, 190, 100, 20);

        jLabel7.setText("Jenis Kelamin");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(40, 220, 100, 20);

        jLabel8.setText("Golongan Darah");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(40, 250, 100, 20);

        jLabel9.setText("Status");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(40, 280, 100, 20);

        jLabel10.setText("Kewarganegaraan");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(40, 310, 100, 20);

        jLabel11.setText("Waktu Praktek");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(40, 340, 100, 20);

        jtxtnama.setEditable(false);
        jPanel1.add(jtxtnama);
        jtxtnama.setBounds(160, 130, 170, 30);

        jtxtalamat.setEditable(false);
        jtxtalamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtalamatActionPerformed(evt);
            }
        });
        jPanel1.add(jtxtalamat);
        jtxtalamat.setBounds(160, 160, 170, 30);

        jtxtusia.setEditable(false);
        jPanel1.add(jtxtusia);
        jtxtusia.setBounds(160, 190, 170, 30);

        jtxtjenis.setEditable(false);
        jPanel1.add(jtxtjenis);
        jtxtjenis.setBounds(160, 220, 170, 30);

        jtxtgol.setEditable(false);
        jPanel1.add(jtxtgol);
        jtxtgol.setBounds(160, 250, 170, 30);

        jtxtstatus.setEditable(false);
        jtxtstatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtstatusActionPerformed(evt);
            }
        });
        jPanel1.add(jtxtstatus);
        jtxtstatus.setBounds(160, 280, 170, 30);

        jtxtkewar.setEditable(false);
        jPanel1.add(jtxtkewar);
        jtxtkewar.setBounds(160, 310, 170, 30);

        jtxtspesial.setEditable(false);
        jPanel1.add(jtxtspesial);
        jtxtspesial.setBounds(160, 340, 170, 30);

        jtxtwaktu.setEditable(false);
        jPanel1.add(jtxtwaktu);
        jtxtwaktu.setBounds(160, 370, 170, 30);

        jPanel2.setBackground(new java.awt.Color(255, 255, 153));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Identitas"));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 308, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 287, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(30, 100, 320, 310);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 400, 420);

        setBounds(0, 0, 416, 458);
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
       if(jComboBox1.getSelectedItem().equals("DR. Farras Yassar")){
        
        jtxtnama.setText("DR. Farras Yassar");
        jtxtalamat.setText("Jl. Surabaya 16, Malang");
        jtxtusia.setText("20 Tahun");
        jtxtjenis.setText("Laki-Laki");
        jtxtgol.setText("A");
        jtxtstatus.setText("Belum Menikah");
        jtxtkewar.setText("Indonesia");
        jtxtspesial.setText("Dokter Umum");
        jtxtwaktu.setText("Pagi (07.00-15.00)");
    }
       else
       if(jComboBox1.getSelectedItem().equals("DR. Anisa Putri")){
        
        jtxtnama.setText("DR. Anisa Putri");
        jtxtalamat.setText("Jl. Veteran 3, Malang");
        jtxtusia.setText("20 Tahun");
        jtxtjenis.setText("Perempuan");
        jtxtgol.setText("O");
        jtxtstatus.setText("Belum Menikah");
        jtxtkewar.setText("Indonesia");
        jtxtspesial.setText("Dokter Gigi");
        jtxtwaktu.setText("Sore (16.00-22.00)");
    }
       else 
       if(jComboBox1.getSelectedItem().equals("DR. Harun Fajar")){
        
        jtxtnama.setText("DR. Harun Fajar");
        jtxtalamat.setText("Jl. Bandung 9, Malang");
        jtxtusia.setText("20 Tahun");
        jtxtjenis.setText("Laki-Laki");
        jtxtgol.setText("B");
        jtxtstatus.setText("Belum Menikah");
        jtxtkewar.setText("Indonesia");
        jtxtspesial.setText("Dokter Gizi");
        jtxtwaktu.setText("Malam (22.00-06.00)");
       }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jtxtalamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtalamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtalamatActionPerformed

    private void jtxtstatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtstatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtstatusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(framearrray.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(framearrray.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(framearrray.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(framearrray.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new framearrray().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jtxtalamat;
    private javax.swing.JTextField jtxtgol;
    private javax.swing.JTextField jtxtjenis;
    private javax.swing.JTextField jtxtkewar;
    private javax.swing.JTextField jtxtnama;
    private javax.swing.JTextField jtxtspesial;
    private javax.swing.JTextField jtxtstatus;
    private javax.swing.JTextField jtxtusia;
    private javax.swing.JTextField jtxtwaktu;
    // End of variables declaration//GEN-END:variables
}
