/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Chrisdaniar
 */
public class Pratikum extends javax.swing.JFrame {

    /**
     * Creates new form Pratikum
     */
    public Pratikum() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        FC = new javax.swing.JCheckBox();
        St = new javax.swing.JCheckBox();
        Kk = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tJumlah = new javax.swing.JTextField();
        tHarga = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        tBaru = new javax.swing.JLabel();
        tTotal = new javax.swing.JLabel();
        tAja = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Besom 2", 1, 36)); // NOI18N
        jLabel1.setText("~Niar ATK~");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(100, 10, 200, 40);

        jLabel2.setText("Nama Barang ");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(50, 70, 90, 14);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Pilih Barang--", "Pensil", "Bulpoin", "Penghapus" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox1);
        jComboBox1.setBounds(160, 70, 160, 20);

        jLabel3.setText("Jumlah");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(50, 200, 60, 14);

        FC.setBackground(new java.awt.Color(204, 204, 255));
        FC.setText("Faber Casstel");
        jPanel1.add(FC);
        FC.setBounds(160, 130, 100, 23);

        St.setBackground(new java.awt.Color(204, 204, 255));
        St.setText("Staddler");
        jPanel1.add(St);
        St.setBounds(230, 100, 100, 23);

        Kk.setBackground(new java.awt.Color(204, 204, 255));
        Kk.setText("Kenko");
        Kk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KkActionPerformed(evt);
            }
        });
        jPanel1.add(Kk);
        Kk.setBounds(160, 100, 60, 23);

        jLabel4.setText("Merk");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(50, 100, 60, 14);

        jLabel5.setText("Harga");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(50, 160, 60, 14);
        jPanel1.add(tJumlah);
        tJumlah.setBounds(160, 200, 160, 30);

        tHarga.setEditable(false);
        jPanel1.add(tHarga);
        tHarga.setBounds(160, 160, 160, 30);

        jButton1.setText("Total");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(140, 240, 73, 23);
        jPanel1.add(tBaru);
        tBaru.setBounds(100, 280, 150, 0);
        jPanel1.add(tTotal);
        tTotal.setBounds(110, 280, 0, 0);
        jPanel1.add(tAja);
        tAja.setBounds(120, 280, 90, 30);

        jLabel8.setText("Rp.");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(90, 290, 70, 14);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 390, 360);

        setBounds(0, 0, 407, 400);
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
         if(jComboBox1.getSelectedItem().equals("Bulpoin")){
             tHarga.setText("3000");
    }
         else if(jComboBox1.getSelectedItem().equals("Pensil")){
             tHarga.setText("2000");
    }
         else  if(jComboBox1.getSelectedItem().equals("Penghapus")){
             tHarga.setText("1500");
    }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void KkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_KkActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int h1 = Integer.parseInt(tHarga.getText());
        int h2 = Integer.parseInt(tJumlah.getText());
        int total = h1*h2;
        
        tAja.setText(String.valueOf(total));
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pratikum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pratikum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pratikum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pratikum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pratikum().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox FC;
    private javax.swing.JCheckBox Kk;
    private javax.swing.JCheckBox St;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel tAja;
    private javax.swing.JLabel tBaru;
    private javax.swing.JTextField tHarga;
    private javax.swing.JTextField tJumlah;
    private javax.swing.JLabel tTotal;
    // End of variables declaration//GEN-END:variables
}
